# Generated by Django 4.0.6 on 2022-07-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_post_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
    ]
