# Generated by Django 4.0.6 on 2022-07-26 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_name_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-update', '-created']},
        ),
    ]
